#!/usr/bin/env python3

from __future__ import annotations

import argparse
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt


def parse_tsp(path: Path) -> tuple[str, dict[int, tuple[int, int]]]:
    name = path.stem
    coords: dict[int, tuple[int, int]] = {}
    in_node_section = False

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line == "EOF":
                break
            if line == "NODE_COORD_SECTION":
                in_node_section = True
                continue
            if not in_node_section:
                if line.startswith("NAME") and ":" in line:
                    name = line.split(":", 1)[1].strip()
                continue

            node_id, x, y = line.split()[:3]
            coords[int(node_id)] = (int(x), int(y))

    if not coords:
        raise ValueError(f"no coordinates found in {path}")

    return name, coords


def parse_route(path: Path) -> list[int]:
    with path.open("r", encoding="utf-8") as handle:
        values = handle.read().split()
    if not values:
        raise ValueError(f"route file {path} is empty")
    return [int(value) for value in values]


def rounded_distance(a: tuple[int, int], b: tuple[int, int]) -> int:
    return round(math.hypot(a[0] - b[0], a[1] - b[1]))


def route_length(route: list[int], coords: dict[int, tuple[int, int]]) -> int:
    total = 0
    for index, node_id in enumerate(route):
        next_node_id = route[(index + 1) % len(route)]
        total += rounded_distance(coords[node_id], coords[next_node_id])
    return total


def render_points(name: str, coords: dict[int, tuple[int, int]], output_dir: Path) -> None:
    xs = [coord[0] for coord in coords.values()]
    ys = [coord[1] for coord in coords.values()]

    figure, axis = plt.subplots(figsize=(10, 10))
    axis.scatter(xs, ys, s=10, color="#1f3c88", alpha=0.8)
    axis.set_title(f"{name} nodes")
    axis.set_aspect("equal", adjustable="box")
    axis.grid(alpha=0.15)
    figure.tight_layout()
    figure.savefig(output_dir / "points.png", dpi=220)
    plt.close(figure)


def render_solution(name: str, route: list[int], coords: dict[int, tuple[int, int]], output_dir: Path) -> None:
    cycle = route + [route[0]]
    xs = [coords[node_id][0] for node_id in cycle]
    ys = [coords[node_id][1] for node_id in cycle]

    figure, axis = plt.subplots(figsize=(10, 10))
    axis.plot(xs, ys, linewidth=1.1, color="#d1495b", alpha=0.9)
    axis.scatter(xs[:-1], ys[:-1], s=10, color="#1f3c88", alpha=0.8)
    axis.set_title(f"{name} tour (length: {route_length(route, coords)})")
    axis.set_aspect("equal", adjustable="box")
    axis.grid(alpha=0.15)
    figure.tight_layout()
    figure.savefig(output_dir / "solution.png", dpi=220)
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate plots for a TSP route.")
    parser.add_argument("--input", required=True, help="Path to the TSPLIB .tsp file")
    parser.add_argument("--route", required=True, help="Path to route.txt generated by main.go")
    parser.add_argument("--output-dir", required=True, help="Directory where PNG files should be saved")
    args = parser.parse_args()

    input_path = Path(args.input)
    route_path = Path(args.route)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    name, coords = parse_tsp(input_path)
    route = parse_route(route_path)

    missing = [node_id for node_id in route if node_id not in coords]
    if missing:
        raise ValueError(f"route contains unknown node IDs: {missing[:5]}")

    render_points(name, coords, output_dir)
    render_solution(name, route, coords, output_dir)
    print(f"Saved plots to {output_dir}")


if __name__ == "__main__":
    main()
